# Generated by Django 2.2.19 on 2021-12-18 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20211217_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='descriptor',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
