# Generated by Django 2.2.6 on 2022-02-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, verbose_name='Текст комментария'),
        ),
    ]
